In [167]:
import time

import torch

print(torch.__version__)

2.3.1


In [ ]:
x = [1, 2, 3, 4, 5]
x = torch.as_tensor(x)
print(x)

In [ ]:
x = torch.zeros(3, 4)
print(x)

In [ ]:
x = torch.ones(3, 4)
print(x)

In [ ]:
x = torch.full((3, 4), fill_value=2)
print(x)

In [ ]:
x = torch.randn(3, 4)
print(x)

In [ ]:
x = torch.randn(3, 4)
y = torch.zeros_like(x)
print(y)

In [ ]:
x = torch.randn(3, 4)
y = torch.ones_like(x)
print(y)

In [ ]:
x = torch.randn(3, 4)
y = torch.full_like(x, 5)
print(y)

In [ ]:
x = torch.zeros(3, 4, dtype=torch.bool)
y = x.new_tensor([1, 2, 3, 4])
print(y)

In [ ]:
x = torch.ones(5, 1)
y = torch.ones(1, 5)
z = x + y
print(z, z.shape)

In [ ]:
x = torch.ones(1, 1, 1, 1, 1)
y = torch.ones(2, 1, 3, 1, 2)
z = x + y
print(z, z.shape)

In [ ]:
x = torch.ones(3, 4, 5)
print(x.mean())
print(x.mean(-1))

In [ ]:
x = torch.ones(3, 4, 5)
print(x.sum(dim=0))
print(x.sum(dim=(1, 2)))

In [ ]:
x = torch.ones(3, 4, 5)
y = x.sum(dim=(1, 2))
z = x.sum(dim=(1, 2), keepdim=True)
print(y, y.shape)
print(z, z.shape)

In [ ]:
x = torch.randn(5, 5)
print(x.to(torch.long))

In [ ]:
x = torch.randn(2, 3, 2)
y = x.view(6, 2)
z = x.view(-1, 2)
print(y, y.shape)
print(z, z.shape)

In [ ]:
x = torch.randn(2, 3, 2)
y = x.permute(1, 2, 0)
print(y, y.shape)

In [ ]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.cat([x, y], dim=0)
print(z, z.shape)

In [ ]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.stack([x, y], dim=1)
print(z, z.shape)

In [ ]:
def add_two_lists(x, y):
    z = []
    for i, j in zip(x, y):
        z.append(i + j)
    return z


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

In [ ]:
def add_two_lists(x, y):
    return x + y


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

In [ ]:
x = torch.randn(3, 3)
y = torch.zeros(5, 2, dtype=torch.long)
print(x.to(torch.float32))
print(x.to(torch.bool))
print(x.to(y))

In [ ]:
x = torch.arange(8)
print(x)
y = torch.arange(2, 8)
print(y)
z = torch.arange(3, 10, step=2)
print(z)

In [ ]:
print(y)
print(torch.select(y, 0, 2))

In [ ]:
x = torch.arange(0, 15)
print(x)

In [ ]:
y = []
for i, v in enumerate(x):
    if i % 3 == 0:
        y.append(v)
torch.stack(y, dim=0)

In [ ]:
a = torch.tensor([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19 , 20], [21, 22, 23, 24]]])

In [ ]:
print(a)

In [ ]:
tensor_3d = torch.tensor([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])

In [ ]:
n, m, _ = tensor_3d.shape
y = torch.zeros(n, m)
for i in range(n):
    for j in range(m):
        maxval = float("-inf")
        for v in tensor_3d[i, j]:
            if v > maxval:
                maxval = v
        y[i, j] = maxval
y

In [ ]:
torch.max(tensor_3d, 2)

In [ ]:
vals, inds = torch.max(tensor_3d, 2)
vals

In [ ]:
torch.max(tensor_3d, 2)[0]

In [ ]:
y = []
for i in x.flatten():
    if i not in y:
        y.append(i)
torch.as_tensor(sorted(y))

In [ ]:
x =torch.tensor([5, 4, 3, 2, 3, 4, 5])

In [ ]:
torch.unique(x, sorted=True)

In [ ]:
x = torch.tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 10.])
y = torch.tensor([3, 4, 5, 6, 7, 8])

In [ ]:
a = 0
b = 0
for i in x.flatten():
    a += i
    b += 1
mean = a / b
c = 0
for i in y.flatten():
    if i > mean:
        c += 1
torch.as_tensor(c)

In [ ]:
(10+9+8+7+6+5+4+3+2+1+0)/11

In [ ]:
torch.mean(x, dim=0)

In [ ]:
torch.where(y > torch.mean(x, dim=0))[0].sum().item()

In [ ]:
torch.tensor(torch.gt(y, torch.mean(x, dim=0)).sum().item())

In [ ]:
torch.mean(x, dim=0)

In [ ]:
x = torch.tensor([[0., 1.], [0.,2.]])

In [ ]:
x

In [ ]:
y = torch.zeros(x.shape[1], x.shape[0])
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        y[j, i] = x[i, j]
y

In [ ]:
torch.flip(torch.flip(x, dims=(-1,0)), dims=(-1,0))

In [ ]:
y = []
for i in range(min(x.shape[0], x.shape[1])):
    y.append(x[i, i])
torch.as_tensor(y)

In [ ]:
torch.diag(x)

In [ ]:
y = []
for i in range(min(x.shape[0], x.shape[1])):
    y.append(x[i, x.shape[1] - i - 1])
torch.as_tensor(y)

In [ ]:
torch.diag(torch.flip(x, [1]))

In [173]:
x = torch.tensor([[0,1,2], [3,4,5], [6,7,8]])
print(x)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [163]:
y = torch.zeros_like(x)
for i in range(0, x.shape[0]):
    for j in range(0, x.shape[1]):
        y[i, j] = x[i, j]
        if i > 0:
            y[i, j] += y[i - 1, j]
        if j > 0:
            y[i, j] += y[i, j - 1]
        if i > 0 and j > 0:
            y[i, j] -= y[i - 1, j - 1]
y

tensor([[ 0,  1,  3],
        [ 3,  8, 15],
        [ 9, 21, 36]])

In [156]:
torch.cumsum(torch.flatten(x), dim=0).view(x.shape)

tensor([[ 0,  1,  3],
        [ 6, 10, 15]])

In [164]:
torch.cumsum(torch.cumsum(x, dim=0), dim=1)

tensor([[ 0,  1,  3],
        [ 3,  8, 15],
        [ 9, 21, 36]])

In [171]:
c = 4

y = torch.zeros_like(x)
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        if x[i, j] < c:
            y[i, j] = 0.0
        else:
            y[i, j] = x[i, j]
y

tensor([[0, 0, 0],
        [0, 4, 5],
        [6, 7, 8]])

In [170]:
torch.where(x < c, torch.tensor(0), x)

tensor([[0, 0, 0],
        [0, 4, 5],
        [6, 7, 8]])

In [168]:
c = torch.tensor(4)

In [169]:
c

tensor(4)

In [174]:
row, col = [], []
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        if x[i, j] < c:
            row.append(i)
            col.append(j)
torch.as_tensor([row, col])

tensor([[0, 0, 0, 1],
        [0, 1, 2, 0]])

In [175]:
torch.nonzero(x < c, as_tuple=False).t()

tensor([[0, 0, 0, 1],
        [0, 1, 2, 0]])

In [177]:
x = torch.tensor([[0,1,2], [3,4,5]])
m = torch.tensor([[True, False, False], [True, True, False]])

y = []
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        if m[i, j]:
            y.append(x[i, j])
torch.as_tensor(y)

tensor([0, 3, 4])

In [181]:
x[m]

tensor([0, 3, 4])

In [190]:
x = torch.tensor([1,2,6,4])
y = torch.tensor([4,5,6,7])

xy = []
for xi in x:
    xy.append(xi)
for yi in y:
    xy.append(yi)

z = []
for xy1, xy2 in zip(xy[1:], xy[:-1]):
    z.append(xy1 - xy2)
torch.as_tensor(z)

tensor([ 1,  4, -2,  0,  1,  1,  1])

In [191]:
count = 0
for xi in x:
    for yi in y:
        if abs(xi - yi) < 1e-3:
            count += 1
            break
torch.as_tensor(count)

tensor(2)

In [195]:
torch.tensor((x.unsqueeze(1) == y).any(dim=1).sum().item())

tensor(2)

In [197]:
a = [[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]]
b = [1., 1., 0.]
torch.tensor(a)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [201]:
torch.Tensor(b)

tensor([1., 1., 0.])

In [212]:
torch.as_tensor(a),torch.as_tensor(b)

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([1., 1., 0.]))

In [210]:
test = torch.as_tensor(a)
test

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [211]:
test.std(dim=1)

tensor([1., 1., 1.])

In [15]:
x = [[7.,8.,9.], [1.,2.,3.], [4.,5.,6.]]
y = [1.,0.,1.]

data = torch.as_tensor(x)
label = torch.as_tensor(y)

print(data)
print(label)

tensor([[7., 8., 9.],
        [1., 2., 3.],
        [4., 5., 6.]])
tensor([1., 0., 1.])


In [16]:
data_mean = data.mean(dim=1)
data_std = data.std(dim=1)

print(data_mean)
print(data_std)

tensor([8., 2., 5.])
tensor([1., 1., 1.])


In [17]:
data_normalized = (data - data_mean)/data_std
print(data_normalized)

tensor([[-1.,  6.,  4.],
        [-7.,  0., -2.],
        [-4.,  3.,  1.]])


In [18]:
input = torch.as_tensor([1,3,5])

input_normalized = (input - data_mean)/data_std
print(input_normalized)

tensor([-7.,  1.,  0.])


In [19]:
[(z - input_normalized).pow(2).sum() for z in data_normalized]

[tensor(77.), tensor(5.), tensor(14.)]

In [20]:
dist = torch.as_tensor([(z - input_normalized).pow(2).sum() for z in data_normalized])

In [21]:
dist

tensor([77.,  5., 14.])

In [22]:
idx = torch.argmin(dist)

In [23]:
idx

tensor(1)

In [28]:
dist

tensor([77.,  5., 14.])

In [34]:
sorted, indices = torch.sort(dist)

indices

tensor([1, 2, 0])

In [37]:
idx, xxxxx = torch.topk(indices, 2)

In [38]:
idx

tensor([2, 1])

In [39]:
data[idx]

tensor([[4., 5., 6.],
        [1., 2., 3.]])

In [40]:
data[idx]

tensor([[4., 5., 6.],
        [1., 2., 3.]])

In [41]:
label[idx]

tensor([1., 0.])

In [42]:
torch.mean(label[idx])

tensor(0.5000)

In [86]:
x = [[3., 10., 1.],
        [5., 4., 2.],
        [7., 8., 100.]]

data = torch.as_tensor(x)

In [74]:
min_values, idx = torch.max(data, dim=1)

In [75]:
min_values

tensor([ 10.,  10., 100.])

In [76]:
values, idx = torch.topk(min_values, 2)

In [77]:
values

tensor([100.,  10.])

In [78]:
torch.topk(min_values, 2)[0]

tensor([100.,  10.])

In [79]:
torch.topk(torch.max(data, dim=1)[0], 2)[0]

tensor([100.,  10.])

In [91]:
data

tensor([[  3.,  10.,   1.],
        [  5.,   4.,   2.],
        [  7.,   8., 100.]])

In [89]:
torch.mean(data, dim=1)

tensor([ 4.6667,  3.6667, 38.3333])

In [93]:
data[0] - torch.mean(data, dim=1)[0]

tensor([-1.6667,  5.3333, -3.6667])

In [110]:
torch.argmax(torch.abs(data - torch.mean(data, dim=1, keepdim=True)), dim=1)

tensor([1, 2, 2])

In [109]:
torch.gather(data, 1, torch.argmax(torch.abs(data - torch.mean(data, dim=1, keepdim=True)), dim=1).unsqueeze(1))

tensor([[ 10.],
        [  2.],
        [100.]])

In [111]:
data - torch.mean(data, dim=1, keepdim=True)

tensor([[ -1.6667,   5.3333,  -3.6667],
        [  1.3333,   0.3333,  -1.6667],
        [-31.3333, -30.3333,  61.6667]])

In [123]:
torch.flip(torch.min(data, dim=1)[0], dims=(0, -1))

RuntimeError: dim 0 appears multiple times in the list of dims

In [132]:
torch.min(data, dim=1)[0].view(-1,1)

tensor([[1.],
        [2.],
        [7.]])

In [133]:
torch.gather(data, 1, torch.argmax(torch.abs(data - torch.mean(data, dim=1, keepdim=True)), dim=1).unsqueeze(1))

tensor([[ 10.],
        [  2.],
        [100.]])

In [137]:
torch.topk(torch.max(data, dim=1)[0], 2)[0].view(-1, 1)

tensor([[100.],
        [ 10.]])

In [146]:
(torch.mean(data, dim=1)[1:] - torch.mean(data, dim=1)[:-1])[torch.argmin(torch.mean(data, dim=1)[1:] - torch.mean(data, dim=1)[:-1])]

tensor(-1.0000)

In [142]:
torch.cumsum(torch.mean(data, dim=1), dim=0)

tensor([ 4.6667,  8.3333, 46.6667])

In [147]:
data

tensor([[  3.,  10.,   1.],
        [  5.,   4.,   2.],
        [  7.,   8., 100.]])

In [148]:
x = torch.as_tensor([5, 6, 7])

In [149]:
x

tensor([5, 6, 7])

In [150]:
data - x

tensor([[-2.,  4., -6.],
        [ 0., -2., -5.],
        [ 2.,  2., 93.]])

In [151]:
torch.abs(data - x)

tensor([[ 2.,  4.,  6.],
        [ 0.,  2.,  5.],
        [ 2.,  2., 93.]])

In [166]:
torch.Tensor.long(torch.argmin(torch.cumsum(torch.abs(data - x), dim=1)[:, -1]))

tensor(1)

In [162]:
torch.cumsum(torch.abs(data - x), dim=1)[:, -1]

tensor([12.,  7., 97.])

In [164]:
torch.cumsum(torch.abs(data - x), dim=1)

tensor([[ 2.,  6., 12.],
        [ 0.,  2.,  7.],
        [ 2.,  4., 97.]])

In [165]:
torch.abs(data - x)

tensor([[ 2.,  4.,  6.],
        [ 0.,  2.,  5.],
        [ 2.,  2., 93.]])

In [171]:
x = torch.as_tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

y = []
for i, v in enumerate(x):
    if i % 3 == 0:
        y.append(v)
        
torch.stack(y, dim=0)

tensor([0., 3., 6., 9.])

In [172]:
x[0::3]

tensor([0., 3., 6., 9.])

In [175]:
x = torch.as_tensor([[[ 1.5674, -0.2373, -0.0274, -1.1008,  0.2859, -0.0296, -1.5471,
           0.6049],
         [ 0.0791,  0.9046, -0.4713,  0.7868, -0.3284, -0.4330,  1.3729,
           2.9334],
         [ 1.5618, -1.6261,  0.6772, -0.8404,  0.9849, -0.1484, -1.4795,
           0.4483],
         [-0.0707,  2.4968,  2.4448, -0.6701, -1.2199,  0.3031, -1.0725,
           0.7276]],

        [[ 0.0511,  1.3095, -0.8022, -0.8504, -1.8068,  1.2523, -1.2256,
           1.2165],
         [-0.9648, -0.2321, -0.3476,  0.3324, -1.3263,  1.1224,  0.5964,
           0.4585],
         [ 0.0540, -1.7400,  0.1156,  0.8032,  0.5411, -1.1646,  0.1476,
          -1.0006],
         [ 0.3801,  0.4733, -0.9103, -0.7830,  0.1351, -0.2116, -1.0406,
          -1.5367]]])


y = torch.as_tensor([[ 0.9374, -0.8830,  1.7457,  2.1346, -0.8561,  0.5408,  0.6169,  1.5160],
        [-1.0447, -0.6641, -0.7239,  1.7507,  0.1753,  0.9928, -0.6279,  0.0770],
        [-1.1641,  1.2473, -0.2706, -1.3635,  1.3066,  0.3231,  1.0358, -0.8625],
        [-1.2575,  0.9418, -1.3257,  0.1467,  0.1691, -1.5397, -0.7276,  1.1491],
        [-0.8746, -0.2977, -1.3707,  0.1150, -1.0188, -0.8378, -2.1057, -0.2604],
        [-1.7149, -0.3379, -1.8263, -0.8390, -1.5723,  0.4580, -0.5653,  0.5428],
        [ 0.1755, -2.2901, -0.7093, -0.2928, -2.1803,  0.0793,  0.9019,  1.2028],
        [-0.5614, -0.1375, -0.1380, -2.0977, -0.7924,  0.6069, -1.4777, -0.5103]])

In [176]:
a = 0
b = 0
for i in x.flatten():
    a += i
    b += 1
mean = a / b
c = 0
for i in y.flatten():
    if i > mean:
        c += 1
torch.as_tensor(c)

tensor(26)

In [186]:
torch.tensor(torch.gt(y, torch.mean(x)).sum().item())

tensor(26)

In [188]:
torch.as_tensor(torch.sum(torch.gt(y, torch.mean(x))))

tensor(26)

In [179]:
torch.gt(y, torch.mean(x, dim=0))

RuntimeError: The size of tensor a (8) must match the size of tensor b (4) at non-singleton dimension 0

In [189]:
x = torch.as_tensor([ -0.9800])
y = torch.as_tensor([-0.9800, -0.0572])

In [190]:
count = 0
for xi in x:
    for yi in y:
        if abs(xi - yi) < 1e-3:
            count += 1
            break
torch.as_tensor(count)

tensor(1)

In [193]:
torch.as_tensor(torch.sum((x.unsqueeze(1) == y).any(dim=1)))

tensor(1)

In [194]:
y = torch.as_tensor([ 0.2345,  0.4975,  0.1104, -0.0738, -0.3271,  0.7549,  0.6801, -0.9512,
        -0.2265, -0.6040])
x = torch.as_tensor([ 0.2345,  0.4975,  0.1104, -0.0738,  0.4979])

In [195]:
count = 0
for xi in x:
    for yi in y:
        if abs(xi - yi) < 1e-3:
            count += 1
            break
torch.as_tensor(count)

tensor(5)

In [196]:
torch.as_tensor(torch.sum((x.unsqueeze(1) == y).any(dim=1)))

tensor(4)

In [199]:
x = torch.as_tensor([[ 0.,  1.],
        [-2., -2.],
        [-1.,  0.]])
y = torch.as_tensor([0., 1., 0.])

In [203]:
tuple[torch.as_tensor(x), torch.as_tensor(y)]

tuple[tensor([[ 0.,  1.],
        [-2., -2.],
        [-1.,  0.]]), tensor([0., 1., 0.])]

In [204]:
tuple[torch.as_tensor(x), torch.as_tensor(y)]

tuple[tensor([[ 0.,  1.],
        [-2., -2.],
        [-1.,  0.]]), tensor([0., 1., 0.])]

In [205]:
type(tuple[torch.as_tensor(x), torch.as_tensor(y)])

types.GenericAlias

In [206]:
type((torch.as_tensor(x), torch.as_tensor(y)))

tuple

In [240]:
x = torch.as_tensor([[ 3., -3.],
        [-2.,  1.],
        [ 4., -1.],
        [ 3.,  0.],
        [ 0.,  4.]])

In [241]:
(x.mean(), x.std())

(tensor(0.9000), tensor(2.5144))

In [244]:
x - x.mean(dim=0)

tensor([[ 1.4000, -3.2000],
        [-3.6000,  0.8000],
        [ 2.4000, -1.2000],
        [ 1.4000, -0.2000],
        [-1.6000,  3.8000]])

In [245]:
(x - x.mean(dim=0))/x.std(dim=0)

tensor([[ 0.5578, -1.2363],
        [-1.4343,  0.3091],
        [ 0.9562, -0.4636],
        [ 0.5578, -0.0773],
        [-0.6375,  1.4681]])

In [266]:
x = torch.as_tensor([[1.0000, 0.2182]])
data_normalized = torch.as_tensor([[ 1.0000,  0.8729],
        [-1.0000, -1.0911],
        [ 0.0000,  0.2182]])

In [267]:
dist = torch.as_tensor([((norm_data - x).pow(2).sum()) for norm_data \
                                 in data_normalized])

In [268]:
dist

tensor([0.4286, 5.7143, 1.0000])

In [269]:
sorted, indices = torch.sort(dist)

In [270]:
print(sorted)
print(indices)

tensor([0.4286, 1.0000, 5.7143])
tensor([0, 2, 1])


In [287]:
data = torch.as_tensor([[74.8000, 88.4000, 54.4000, 56.6000, 65.3000, 81.7000, 74.5000, 94.8000,72.7000, 81.6000],[67.4000, 70.0000, 51.1000, 58.4000, 64.6000, 75.9000, 84.8000, 90.0000,58.0000, 64.1000]])

In [272]:
data

tensor([[74.8000, 88.4000, 54.4000, 56.6000, 65.3000, 81.7000, 74.5000, 94.8000,
         72.7000, 81.6000],
        [67.4000, 70.0000, 51.1000, 58.4000, 64.6000, 75.9000, 84.8000, 90.0000,
         58.0000, 64.1000]])

In [274]:
torch.as_tensor(data).view(-1, 10)

tensor([[74.8000, 88.4000, 54.4000, 56.6000, 65.3000, 81.7000, 74.5000, 94.8000,
         72.7000, 81.6000],
        [67.4000, 70.0000, 51.1000, 58.4000, 64.6000, 75.9000, 84.8000, 90.0000,
         58.0000, 64.1000]])

In [277]:
torch.min(data, dim=1)[0].view(-1,1), torch.max(data, dim=1)[0].view(-1, 1)

(tensor([[54.4000],
         [51.1000]]),
 tensor([[94.8000],
         [90.0000]]))

In [280]:
(torch.min(data, dim=1)[0].view(-1,1)).shape

torch.Size([2, 1])

In [286]:
torch.squeeze(torch.as_tensor((torch.min(data, dim=1)[0].view(-1,1)))).shape

torch.Size([2])

In [292]:
data
k=1

In [311]:
torch.mean(data[-k:])

tensor(68.4300)

In [309]:
data[-k:]

tensor([[67.4000, 70.0000, 51.1000, 58.4000, 64.6000, 75.9000, 84.8000, 90.0000,
         58.0000, 64.1000]])

In [ ]:
x = 